name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '7.0.x'

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GHCR_TOKEN }}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/${{ github.repository }}:latest
              docker push ghcr.io/${{ github.repository }}:latest
